name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.5.1
        name: Setup Node
      - name: Install dependencies
        run: npm i
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Download dependencies
        run: echo Hello, world!
      - name: run test
        run: npm run test